services:
  dev-relay-your-ip:
    container_name: dev-relay-your-ip
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /etc/localtime:/etc/localtime:ro