version: '3'

services:
  dev-relay-your-ip:
    container_name: dev-relay-your-ip
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /etc/localtime:/etc/localtime:ro